### ISSUE TITLE
Proofread, finalize and streamline documentation and help texts

### ISSUE THREAD

**Issue by rwinterschlaf** [Leibniz-HBI/newsfeedback#18]
Self-explanatory :)

**Comment by FlxVctr** [comment]
For click applications, I always try to make the help dialogue as useful as possible. This can then easily be used in the README/Docs. (see e.g. https://github.com/Leibniz-HBI/twacapic#usage)

**Comment by rwinterschlaf** [comment]
Has been resolved in newest merge, though will surely continue to be an on-going to-do.
