### ISSUE TITLE
Resolve date_parser/pyzt warning

### ISSUE THREAD

**Issue by rwinterschlaf** [Leibniz-HBI/newsfeedback#4]
`PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)`

Error taken from the tool testing private repository. Doesn't impact functionality but is quite annoying.  So far has only plopped up when extracting metadata from https://www.badische-zeitung.de/

**Comment by FlxVctr** [comment]
I guess this is coming from Trafilatura, trying to extract dates? Maybe report to their repo, if you can confirm.

**Comment by rwinterschlaf** [comment]
Fixed thanks to updating dateparser.
