### ISSUE TITLE
Setup Github actions to test on unix system

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/newsfeedback#7]

**Comment by FlxVctr** [comment]
@rwinterschlaf until then let me know if I should run tests for a PR on MacOS/POSIX. Or are you already working in Windows subsystem for Linux?

**Comment by rwinterschlaf** [comment]
Thanks @FlxVctr ! Would be good if you could do this - I am working in my usual Windows setup, so no Linux in sight.

**Comment by FlxVctr** [comment]
Long term it might be good to try this: https://smo-wiki.leibniz-hbi.de/Windows-Linux-Subsystem-dev-setup

**Comment by rwinterschlaf** [comment]
Since these are up and running now, I'll close the issue.
